#!/bin/bash

echo "Task1"

PVT="$(python2 -V 2>&1 | grep -o '[0-9]' | head -1 )"
pvt1="$(python2 -V 2>&1)"
echo "Python version2 $pvt1"

PVTT="$(python3 -V | grep -o '[0-9]' | head -1 )"
pvt2="$(python3 -V)"
echo "Python3 version $pvt2"


if  [ $PVTT >  $PVT ] ;then
	echo "Python version $pvt2 is the best"
else
	echo "Python version $pvt1 is the best  "
fi


